
package com.sample.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MathWS", targetNamespace = "http://sample.com/", wsdlLocation = "file:/C:/Users/VimalPS/AppData/Local/Temp/tempdir7880760927438415464.tmp/JAX-WS-EP-1_1.wsdl")
public class MathWS
    extends Service
{

    private final static URL MATHWS_WSDL_LOCATION;
    private final static WebServiceException MATHWS_EXCEPTION;
    private final static QName MATHWS_QNAME = new QName("http://sample.com/", "MathWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/VimalPS/AppData/Local/Temp/tempdir7880760927438415464.tmp/JAX-WS-EP-1_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATHWS_WSDL_LOCATION = url;
        MATHWS_EXCEPTION = e;
    }

    public MathWS() {
        super(__getWsdlLocation(), MATHWS_QNAME);
    }

    public MathWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATHWS_QNAME, features);
    }

    public MathWS(URL wsdlLocation) {
        super(wsdlLocation, MATHWS_QNAME);
    }

    public MathWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATHWS_QNAME, features);
    }

    public MathWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleMath
     */
    @WebEndpoint(name = "MathWSPort")
    public SimpleMath getMathWSPort() {
        return super.getPort(new QName("http://sample.com/", "MathWSPort"), SimpleMath.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleMath
     */
    @WebEndpoint(name = "MathWSPort")
    public SimpleMath getMathWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sample.com/", "MathWSPort"), SimpleMath.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATHWS_EXCEPTION!= null) {
            throw MATHWS_EXCEPTION;
        }
        return MATHWS_WSDL_LOCATION;
    }

}
